import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ScreenProvider from "@/context/ScreenContext";
import MsjsProvider from "@/context/LoadingMsjContext";
import CartProvider from "@/context/CartContext";
import PayProvider from "@/context/PayContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ecommerce Gaming",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
             <ScreenProvider>
        <MsjsProvider>
          <CartProvider>
            <PayProvider>
              {children}
            </PayProvider>
          </CartProvider>
        </MsjsProvider>
      </ScreenProvider>
      </body>
    </html>
  );
}
